### ISSUE TITLE
Author's Issue: Please delete this repository or change to private repository.

### ISSUE THREAD

**Issue by Stereoarts** [FlowingCrescent/CelShadingWithFringeShadow_URP#1]
I don't permit to upload my copyrights(codes, images, models, motions, and documents) to public space. Please delete this repository or change to private repository.

So you must check model / motion's licenses. Almost models and motions aren't permitted using without MMD and redistribution.

You should check all licenses again. (Readme.txt, ...)

**Comment by Stereoarts** [comment]
If you can't understand for this issue, I'll discontinue to support for foreign users.

**Comment by Stereoarts** [comment]
Did you check this?

https://github.com/FlowingCrescent/CelShadingWithFringeShadow_URP/blob/master/Assets/Models/Cel_Characters/F.%E5%BC%8F%E3%82%AD%E3%83%A3%E3%83%AB%20ver1.0/(English)ReadMe.txt

**Comment by FlowingCrescent** [comment]
> I don't permit to upload my copyrights(codes, images, models, motions, and documents) to public space. Please delete this repository or change to private repository.
> 
> So you must check model / motion's licenses. Almost models and motions aren't permitted using without MMD and redistribution.
> 
> You should check all licenses again. (Readme.txt, ...)

I'm very sorry for forgetting the rule of prohibiting redistribution, now I deleted the unauthorized model.
I promise I won't make the same mistake again.
Apologize to you and model author again.
